graph TD
    A["30 | 60"] --> B["10 | 20"]
    A --> C["40 | 50"]
    A --> D["70 | 80 | 90"]

    B --> E[10]
    B --> F[20]

    C --> G[40]
    C --> H[50]

    D --> I[70]
    D --> J[80]
    D --> K[90]
