-- MySQL Script generated by MySQL Workbench
-- Tue Mar 19 21:12:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SAM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SAM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAM` DEFAULT CHARACTER SET utf8 ;
USE `SAM` ;

-- -----------------------------------------------------
-- Table `SAM`.`AREA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`AREA` (
  `sigla` VARCHAR(7) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `superArea` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`sigla`),
  INDEX `fk_AREA_AREA_idx` (`superArea` ASC) VISIBLE,
  CONSTRAINT `fk_AREA_AREA`
    FOREIGN KEY (`superArea`)
    REFERENCES `SAM`.`AREA` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`ALUNO` (
  `CPF` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `dataNasc` DATE NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`CURSO` (
  `sigla` VARCHAR(7) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `horas` INT NOT NULL,
  `custo` FLOAT NOT NULL,
  `area` VARCHAR(7) NOT NULL,
  `ALUNO_CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`sigla`, `ALUNO_CPF`),
  INDEX `fk_CURSO_AREA1_idx` (`area` ASC) VISIBLE,
  INDEX `fk_CURSO_ALUNO1_idx` (`ALUNO_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_AREA1`
    FOREIGN KEY (`area`)
    REFERENCES `SAM`.`AREA` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_ALUNO1`
    FOREIGN KEY (`ALUNO_CPF`)
    REFERENCES `SAM`.`ALUNO` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`PROFESSOR` (
  `cpf` VARCHAR(11) NOT NULL,
  `curso` VARCHAR(7) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`, `curso`),
  INDEX `fk_PROFESSOR_CURSO1_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESSOR_CURSO1`
    FOREIGN KEY (`curso`)
    REFERENCES `SAM`.`CURSO` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`MATRICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`MATRICULA` (
  `data` INT NOT NULL,
  `pago` INT NOT NULL,
  `curso` VARCHAR(7) NOT NULL,
  `ALUNO_CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`curso`, `ALUNO_CPF`),
  INDEX `fk_MATRICULA_ALUNO1_idx` (`ALUNO_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_MATRICULA_CURSO1`
    FOREIGN KEY (`curso`)
    REFERENCES `SAM`.`CURSO` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATRICULA_ALUNO1`
    FOREIGN KEY (`ALUNO_CPF`)
    REFERENCES `SAM`.`ALUNO` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`MODULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`MODULO` (
  `sigla` VARCHAR(7) NOT NULL,
  `curso` VARCHAR(7) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sigla`),
  INDEX `fk_MODULO_CURSO1_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_MODULO_CURSO1`
    FOREIGN KEY (`curso`)
    REFERENCES `SAM`.`CURSO` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAM`.`TOPICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAM`.`TOPICO` (
  `sigla` VARCHAR(7) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `horas` INT NOT NULL,
  `modulo` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`sigla`, `modulo`),
  INDEX `fk_TOPICO_MODULO1_idx` (`modulo` ASC) VISIBLE,
  CONSTRAINT `fk_TOPICO_MODULO1`
    FOREIGN KEY (`modulo`)
    REFERENCES `SAM`.`MODULO` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
